baseurl = "/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Yifei Liu"
title = "Yifei Liu"
disqusshortname = "datascience"
pluralizelisttitles = false
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Blog by Yifei Liu"
copyright = "Copyright © 2018 Yifei Liu"

logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
highlightjsVersion = "9.11.0"
share = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
highlightjsCDN = "https://cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
progressively = true
latestpostcount = 5
github = "moxiaoran"
email = "you@example.com"
linkedin = "john-example-aa80ue8è"
twitter = "example"
facebook = "facebook_id"
instagram = "instagram_id"
itch_io = "itch_io_id"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = false
[params.colors]
# identifier = "#527fc1f"
# identifier_dark = "#1a3152"
# trivial = "#6a7a8b"
# foreground = "#181d2a"
# background = "#f9f9f9"
# background_dark = "#282a36"
# code = "#87a5d2"
# type = "#97d28b"
# special = "#ffcb8d"
# value = "#96c2d7"
# statement = "#ff8e91"
